In [1]:
import numpy as np

In [2]:
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5,'sudh',4+4j])

array(['1', '2', '3', '4', '5', 'sudh', '(4+4j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5,6.0]) #Automatically do the type casting.

array([1. , 2. , 3. , 4.5, 6. ])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
np.array([[1,3],[3,4],[6,7]])  

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([(1,3),(3,4),(6,7)])  #Both line is same representation.

array([[1, 3],
       [3, 4],
       [6, 7]])

In [10]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\HP\AppData\Local\Temp\ipykernel_4316\1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [11]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [12]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [13]:
np.array([1,2,3], ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
arr=np.array([(1,2),(4,5)],dtype=[("a",'<i2'),('b','<i8')]) 
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [16]:
arr[0]

(1, 2)

In [17]:
arr[0][0]

1

In [18]:
type(arr[0][0])

numpy.int16

In [19]:
type(arr[0][1])

numpy.int64

In [20]:
arr=np.array([(1,2),(4,5)],dtype=[("a",'<i4'),('b','<i8')]) 
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [21]:
type(arr[0][0])

numpy.int32

In [22]:
type(arr[0][1])

numpy.int64

In [23]:
arr=np.array([(1,2),(4,5)])
arr

array([[1, 2],
       [4, 5]])

In [24]:
print(arr[0][0])
print(arr[0][1])
print(arr[1][0])
print(arr[1][1])

1
2
4
5


In [25]:
type(arr[0][1])

numpy.int32

In [26]:
np.mat(arr)

matrix([[1, 2],
        [4, 5]])

In [27]:
l=[3,4,5,6,7]

In [28]:
np.array(l)

array([3, 4, 5, 6, 7])

In [29]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [30]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [31]:
mat=np.mat(arr)
mat

matrix([[1, 2],
        [4, 5]])

In [32]:
np.asanyarray(mat) #Here matrix is type of arrary.

matrix([[1, 2],
        [4, 5]])

In [33]:
np.asarray(mat)

array([[1, 2],
       [4, 5]])

In [34]:
issubclass(np.matrix,np.ndarray)

True

In [35]:
issubclass(np.ndarray,np.matrix)

False

In [36]:
arr

array([[1, 2],
       [4, 5]])

In [37]:
a=arr #shallow copy (a and arr point same location of memory.)

In [38]:
b=np.copy(arr) #deep copy (b is another location copy all the data into memory.)

In [39]:
arr[0][0]=86 #array is mutable.

In [40]:
arr

array([[86,  2],
       [ 4,  5]])

In [41]:
a

array([[86,  2],
       [ 4,  5]])

In [42]:
b

array([[1, 2],
       [4, 5]])

In [44]:
arr[:]

array([[86,  2],
       [ 4,  5]])

In [45]:
arr[-1]

array([4, 5])

In [46]:
for i in arr:
    print(i)

[86  2]
[4 5]


In [47]:
np.fromfunction(lambda i, j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [48]:
type(np.fromfunction(lambda i, j : i==j, (4,4)))

numpy.ndarray

In [49]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
np.fromfunction(lambda i, j : i**j, (4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [52]:
np.fromfunction(lambda i, j : i/j, (3,3))

C:\Users\HP\AppData\Local\Temp\ipykernel_4316\3524157497.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j : i/j, (3,3))
C:\Users\HP\AppData\Local\Temp\ipykernel_4316\3524157497.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j : i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [53]:
1/0

ZeroDivisionError: division by zero

In [54]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [61]:
gen=(i*i for i in range(5))
gen

<generator object <genexpr> at 0x00000142F80467B0>

In [60]:
def test(x):
    yield x
test(5)

<generator object test at 0x00000142F8046660>

In [62]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [66]:
np.fromstring('1,3,4,5,5',sep=',')

array([1., 3., 4., 5., 5.])

In [67]:
np.fromstring('1,3,4,5,5',sep=',',dtype=int)

array([1, 3, 4, 5, 5])

In [69]:
np.fromstring('945 454 4545 454', sep=' ', dtype=complex)

array([ 945.+0.j,  454.+0.j, 4545.+0.j,  454.+0.j])

In [70]:
l=[1,2,3,4,5,6]

In [72]:
arr=np.array(l)

In [76]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [74]:
type(arr)

numpy.ndarray

In [77]:
arr1.ndim

2

In [78]:
arr1.size

12

In [79]:
arr1.shape

(3, 4)

In [80]:
arr1.dtype

dtype('int32')

In [81]:
arr

array([1, 2, 3, 4, 5, 6])

In [82]:
arr.size

6

In [83]:
arr.ndim

1

In [84]:
arr.shape

(6,)

In [85]:
arr3=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [86]:
arr3.size

16

In [87]:
arr3.ndim

3

In [88]:
arr3.shape # Here (2,4) array happened 2 times.

(2, 2, 4)

In [91]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [92]:
arr4.size

32

In [93]:
arr4.ndim

4

In [94]:
arr4.shape # Here (2,4) array 4 times(layer) in 4D 1 object.

(1, 4, 2, 4)

In [95]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [96]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [98]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [99]:
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [100]:
    np.arange(6.6,9,-0.3)

array([], dtype=float64)

In [101]:
np.arange(9,6.6,-0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [102]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
 np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [105]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [106]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [107]:
np.linspace(.3,.5,3)

array([0.3, 0.4, 0.5])

In [108]:
np.linspace(.1,.11,5)

array([0.1   , 0.1025, 0.105 , 0.1075, 0.11  ])

In [109]:
np.linspace(1,10,5) #9/5 equal part

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [111]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [112]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [114]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [115]:
np.ones(4)

array([1., 1., 1., 1.])

In [117]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [118]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [119]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [120]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [121]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [122]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [124]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [125]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [127]:
np.logspace([2],[3])

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [128]:
d=np.linspace(4,7,40)

In [129]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [130]:
d.ndim

1

In [131]:
d.shape

(40,)

In [132]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [133]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [134]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [135]:
np.random.rand(3)

array([0.79942336, 0.93815507, 0.65962944])

In [136]:
np.random.randint(5)

0

In [137]:
np.random.randn(5,4)

array([[-0.48222314,  1.37906869, -0.23314596, -0.92264507],
       [ 0.16831277, -0.76255449,  0.97491748,  1.82485771],
       [-1.05707636,  0.02767298,  0.37729491,  1.12278594],
       [ 1.54563441,  0.23829315, -0.63462333, -1.10402855],
       [ 0.50258857, -0.35450101,  1.41306868, -0.8062784 ]])

In [138]:
np.random.randn(2,3)

array([[-0.62434556, -1.30692288, -1.49770155],
       [-0.59872777,  1.44630149,  0.507407  ]])

In [140]:
np.random.randn(2,2,3)

array([[[-1.12376691, -0.95558943,  2.17060976],
        [ 0.31533634, -0.06206403,  0.00893183]],

       [[-1.44417612, -2.49895978, -0.26227038],
        [-1.57866315, -0.25300018,  0.69809078]]])

In [141]:
np.random.randint(5)

4

In [142]:
np.random.randint(5,60)

49

In [143]:
np.random.randint(5,60,(4,4))

array([[11, 59, 19, 14],
       [51, 49, 50, 48],
       [53, 18, 46,  7],
       [16, 13, 26, 27]])

In [146]:
arr=np.random.randint(3,9,(3,3))
arr

array([[8, 3, 7],
       [5, 4, 7],
       [5, 4, 3]])

In [147]:
arr.reshape(1,9)

array([[8, 3, 7, 5, 4, 7, 5, 4, 3]])

In [148]:
arr.reshape(9,1)

array([[8],
       [3],
       [7],
       [5],
       [4],
       [7],
       [5],
       [4],
       [3]])

In [149]:
arr.reshape(1,1,9)

array([[[8, 3, 7, 5, 4, 7, 5, 4, 3]]])

In [150]:
arr.reshape(3,3,1)

array([[[8],
        [3],
        [7]],

       [[5],
        [4],
        [7]],

       [[5],
        [4],
        [3]]])

In [151]:
arr.reshape(3,-1)

array([[8, 3, 7],
       [5, 4, 7],
       [5, 4, 3]])

In [152]:
arr.reshape(3,-14093904)

array([[8, 3, 7],
       [5, 4, 7],
       [5, 4, 3]])

In [153]:
arr.reshape(4,-14093904)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [154]:
arr.max()

8

In [155]:
arr.min()

3

In [156]:
arr.mean()

5.111111111111111

In [157]:
arr=np.random.randint(4,10,(5,5))

In [158]:
arr

array([[7, 5, 9, 9, 4],
       [4, 7, 8, 8, 5],
       [4, 4, 4, 6, 7],
       [6, 5, 8, 8, 4],
       [8, 9, 5, 4, 5]])

In [160]:
arr[3:,3:]

array([[8, 4],
       [4, 5]])

In [161]:
arr[:,[1,3]]

array([[5, 9],
       [7, 8],
       [4, 6],
       [5, 8],
       [9, 4]])

In [162]:
arr[[1,3],:]

array([[4, 7, 8, 8, 5],
       [6, 5, 8, 8, 4]])

In [163]:
arr

array([[7, 5, 9, 9, 4],
       [4, 7, 8, 8, 5],
       [4, 4, 4, 6, 7],
       [6, 5, 8, 8, 4],
       [8, 9, 5, 4, 5]])

In [170]:
arr>7

array([[False, False,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [ True,  True, False, False, False]])

In [171]:
arr[arr>7]

array([9, 9, 8, 8, 8, 8, 8, 9])

In [172]:
arr*arr

array([[49, 25, 81, 81, 16],
       [16, 49, 64, 64, 25],
       [16, 16, 16, 36, 49],
       [36, 25, 64, 64, 16],
       [64, 81, 25, 16, 25]])

In [173]:
arr1=np.random.randint(2,4,(3,3))
arr2=np.random.randint(2,4,(3,3))

In [174]:
arr1

array([[3, 3, 3],
       [2, 2, 3],
       [2, 2, 2]])

In [175]:
arr2

array([[2, 3, 3],
       [2, 3, 3],
       [2, 2, 3]])

In [176]:
arr1*arr2

array([[6, 9, 9],
       [4, 6, 9],
       [4, 4, 6]])

In [177]:
arr1@arr2

array([[18, 24, 27],
       [14, 18, 21],
       [12, 16, 18]])

In [178]:
arr/0

C:\Users\HP\AppData\Local\Temp\ipykernel_4316\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [179]:
arr*2

array([[14, 10, 18, 18,  8],
       [ 8, 14, 16, 16, 10],
       [ 8,  8,  8, 12, 14],
       [12, 10, 16, 16,  8],
       [16, 18, 10,  8, 10]])

In [180]:
arr=np.zeros((3,4))

In [181]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [182]:
a=np.array([1,2,3,4])

In [183]:
a

array([1, 2, 3, 4])

In [184]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [186]:
b=np.array([5,6,7])

In [187]:
b

array([5, 6, 7])

In [188]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [189]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [190]:
b

array([5, 6, 7])

In [192]:
b=np.array([[4,5,6]])

In [193]:
b

array([[4, 5, 6]])

In [194]:
b.T

array([[4],
       [5],
       [6]])

In [195]:
b.T +arr

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [196]:
arr=np.random.rand(5,4)

In [197]:
arr

array([[0.11876079, 0.09223314, 0.09523645, 0.52047544],
       [0.44311716, 0.33878872, 0.40533051, 0.09402976],
       [0.27584836, 0.22418775, 0.24224751, 0.34470527],
       [0.08181174, 0.77210286, 0.09648619, 0.46368318],
       [0.15800206, 0.77828231, 0.99916129, 0.80988256]])

In [198]:
np.sqrt(arr)

array([[0.34461688, 0.3036991 , 0.30860403, 0.72143984],
       [0.66567046, 0.5820556 , 0.63665572, 0.30664272],
       [0.52521268, 0.47348469, 0.49218646, 0.58711606],
       [0.28602752, 0.87869384, 0.31062226, 0.68094286],
       [0.39749473, 0.8822031 , 0.99958056, 0.89993475]])

In [199]:
np.exp(arr)

array([[1.12610052, 1.09662046, 1.0999189 , 1.68282754],
       [1.55755481, 1.40324683, 1.49979811, 1.09859244],
       [1.31764804, 1.25130593, 1.2741095 , 1.41157383],
       [1.08525148, 2.16431272, 1.10129437, 1.58991917],
       [1.17116861, 2.17772839, 2.71600294, 2.247644  ]])

In [200]:
np.log10(arr)

array([[-9.25326906e-01, -1.03511299e+00, -1.02119680e+00,
        -2.83599762e-01],
       [-3.53481430e-01, -4.70071061e-01, -3.92190709e-01,
        -1.02673468e+00],
       [-5.59329589e-01, -6.49388124e-01, -6.15740684e-01,
        -4.62552074e-01],
       [-1.08718436e+00, -1.12324839e-01, -1.01553484e+00,
        -3.33778658e-01],
       [-8.01337242e-01, -1.08862840e-01, -3.64398838e-04,
        -9.15779553e-02]])

In [201]:
arr1=np.random.randint(2,5,(5,5))

In [202]:
np.log(arr1)

array([[1.38629436, 1.38629436, 1.38629436, 0.69314718, 0.69314718],
       [1.38629436, 1.09861229, 1.38629436, 1.38629436, 1.09861229],
       [1.09861229, 0.69314718, 0.69314718, 1.09861229, 1.09861229],
       [1.09861229, 0.69314718, 0.69314718, 1.09861229, 0.69314718],
       [1.09861229, 1.09861229, 0.69314718, 1.38629436, 1.38629436]])

In [203]:
np.log2(arr1)

array([[2.       , 2.       , 2.       , 1.       , 1.       ],
       [2.       , 1.5849625, 2.       , 2.       , 1.5849625],
       [1.5849625, 1.       , 1.       , 1.5849625, 1.5849625],
       [1.5849625, 1.       , 1.       , 1.5849625, 1.       ],
       [1.5849625, 1.5849625, 1.       , 2.       , 2.       ]])

In [204]:
np.random.rand(2,4)

array([[0.02003134, 0.78034873, 0.1833073 , 0.91957455],
       [0.68607116, 0.24046939, 0.04542624, 0.66791331]])

In [209]:
np.random.seed(3)
np.random.rand(2,4)

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761],
       [0.89294695, 0.89629309, 0.12558531, 0.20724288]])